from . import res_company
from . import res_config_settings
from . import res_location_pa
from . import res_partner
from . import hka_service
from . import account_move
from . import pos_config
from . import pos_session
from . import pos_order
from . import pos_payment_method